defaults:
  - _self_


# Disable Hydra's automatic chdir if you want your project_root to remain the same as when you launch the command.
hydra:
  job:
    chdir: false

run_hyperparameter_tuning: false
submit_to_kaggle: false

mlflow:
  experiment_name: kaggle_nlp_getting_started
  run_id: null
  tags:
    features: count_vectorizer
    model: lgbm

kaggle_competition: nlp-getting-started

project_root: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started

data:
  data_dir: ${project_root}/data
  raw_dir: ${data.data_dir}/raw
  split_dir: ${data.data_dir}/splits
  submissions_dir: ${data.data_dir}/submissions

  raw_train_path: ${data.raw_dir}/train.csv
  raw_test_path: ${data.raw_dir}/test.csv
  raw_sample_submission_path: ${data.raw_dir}/sample_submission.csv

  train_split_path: ${data.split_dir}/train.parquet
  val_split_path: ${data.split_dir}/val.parquet
  test_split_path: ${data.split_dir}/test.parquet

split_params:
  train_frac: 0.8
  val_frac: 0.1
  test_frac: 0.1
  train_val_test_seed: 42

model_params:
  num_leaves: 31
  n_estimators: 200
  learning_rate: 0.15
  max_depth: -1
  random_state: 42
  boosting_type: 'gbdt'
  verbose: -1

hyperparameter_tuning:
  n_trials: 20
  parameters:
    n_estimators:
      type: int
      low: 100
      high: 300
    learning_rate:
      type: float
      low: 0.05
      high: 0.20
      log: false
    num_leaves:
      type: int
      low: 10
      high: 50
    boosting_type:
      type: categorical
      choices: ["gbdt", "dart", "goss"]
    max_depth:
      type: int
      low: 2
      high: 100


