defaults:
  - _self_


# Disable Hydra's automatic chdir if you want your project_root to remain the same as when you launch the command.
hydra:
  job:
    chdir: false

project_root: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started

mlflow:
  experiment_name: kaggle_nlp_getting_started
  tags:
    model: lgbm

raw_data:
  train_path: ${project_root}/data/train.csv
  test_path: ${project_root}/data/test.csv
  sample_submission_path: ${project_root}/data/sample_submission.csv

training_data:
  train_path: ${project_root}/data/splits/train.parquet
  val_path: ${project_root}/data/splits/val.parquet
  test_path: ${project_root}/data/splits/test.parquet

params:
  train_frac: 0.8
  test_frac: 0.2
  train_val_test_seed: 42

model_params:
  num_leaves: 31
  n_estimators: 200
  learning_rate: 0.15
  max_depth: -1
  random_state: 42
  boosting_type: 'gbdt'
  verbose: -1

hyperparameter_tuning:
  n_trials: 10
  parameters:
    n_estimators:
      type: int
      low: 100
      high: 300
    learning_rate:
      type: float
      low: 0.05
      high: 0.20
      log: false
    num_leaves:
      type: int
      low: 10
      high: 50
    boosting_type:
      type: categorical
      choices: ["gbdt", "dart", "goss"]

experiment:
  submit_to_kaggle: false
  tuning: true

kaggle:
  data_dir: ${project_root}/data/kaggle
  competition: nlp-getting-started
  train_file: ${project_root}/data/kaggle/train.csv
  test: new_test_value
