run_hyperparameter_tuning: true
submit_to_kaggle: false
mlflow:
  experiment_name: kaggle_nlp_getting_started
  tags:
    features: count_vectorizer
    model: lgbm
kaggle_competition: nlp-getting-started
project_root: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started
data:
  data_dir: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data
  raw_dir: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/raw
  split_dir: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/splits
  submissions_dir: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/submissions
  raw_train_path: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/raw/train.csv
  raw_test_path: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/raw/test.csv
  raw_sample_submission_path: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/raw/sample_submission.csv
  train_split_path: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/splits/train.parquet
  val_split_path: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/splits/val.parquet
  test_split_path: /Users/traviswhitfield/Documents/github/kaggle_nlp_getting_started/data/splits/test.parquet
split_params:
  train_frac: 0.8
  val_frac: 0.1
  test_frac: 0.1
  train_val_test_seed: 42
model_params:
  num_leaves: 15
  n_estimators: 265
  learning_rate: 0.17269970089639117
  max_depth: 82
  random_state: 42
  boosting_type: gbdt
  verbose: -1
hyperparameter_tuning:
  n_trials: 20
  parameters:
    n_estimators:
      type: int
      low: 100
      high: 300
    learning_rate:
      type: float
      low: 0.05
      high: 0.2
      log: false
    num_leaves:
      type: int
      low: 10
      high: 50
    boosting_type:
      type: categorical
      choices:
      - gbdt
      - dart
      - goss
    max_depth:
      type: int
      low: 2
      high: 100
